### PR TITLE
Display claw sabers

### PR DESCRIPTION
**Pull request by piepie62**
Got fed up with having trail-only claws, so I decided to do something about it. Note that no trails currently display. I'm not sure if there's supposed to be a trail bundled in with the claws saber, but if there is, I haven't found how to access and use it. I briefly considered trying to figure out how to get the default trail to show for the claws, but it didn't quite make sense to me to have a single trail coming out of the middle claw only (which wouldn't follow the curve of the claw properly, either) and I have no idea how I would get three of them to display at once

### CODE REVIEW

**Comment by SteffanDonal** [comment]
Thank you!

I will take a look, test and see about restoring the trail before releasing an update.

**Comment by piepie62** [comment]
I just realized that I didn't properly dispose of the resource stream before. Fixed that. Can you tell that I'm not well-versed in C# yet?
(Force push below because I accidentally didn't have my line endings set properly, making the entire file say it was changed)

**Comment by piepie62** [comment]
Okay, I've figured out what I was doing wrong with the vanilla trail. Now, since I can't open the saber itself, I have to ask: is there a custom trail attached to it? If so, I'll try to adapt what I'm doing with the vanilla one.
That said, I have also figured out how to have three trails, with one positioned within each claw. I'm not sure whether this is a desired effect or not, and can fairly easily remove it if desired.
The final thing I have to mention is a slight issue I have with the claws model itself: the current model's back is open, so it's very easy to see the trail just kind of appearing out of nowhere. Could you possibly fix that? I'd do it myself, but as I said above, I don't have a way to open and edit it.

**Comment by piepie62** [comment]
Another note I want to make: the vanilla trail as it is in the commit above is a little too long and sticks out the front of the claws. I'd rather not hardcode it to be 0.25f long (at which size it's entirely inside), but I can do that if no better option comes up and that change is desirable.

**Comment by piepie62** [comment]
Came up with a solution to the above: trails are now 75% the length of the saber, as set by the preferences class

**Comment by SteffanDonal** [comment]
Beautiful, thanks again - I will endeavour to check it out today/tomorrow! Work is exhausting during the week ❤️

**Pull request merged**
